AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeWithMe project to accept URL's and process them

Resources:
  PostHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.codewithme.apirouter.Handler
      Runtime: java8
      MemorySize: 256
      Timeout: 25
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /
            Method: put
